export const carData = [
  {
    id: 1,
    type: "Truck",
    price_per_day: 85,
    capacity: 2,
    brand: "Ford",
    image: require('../asset/imagesFolder/sedanCar.jpg'),
  },
  {
    id: 2,
    type: "Bike",
    price_per_day: 20,
    capacity: 1,
    brand: "Yamaha",
    image: require('../asset/imagesFolder/cat1.png'),
  },
  {
    id: 3,
    type: "Van",
    price_per_day: 90,
    capacity: 8,
    brand: "Mercedes-Benz",
    image: require('../asset/imagesFolder/dog1.png'),
  },
  {
    id: 4,
    type: "Sedan",
    price_per_day: 55,
    capacity: 5,
    brand: "Honda",
    image: require('../asset/imagesFolder/sedanCar.jpg'),
  },
  {
    id: 5,
    type: "SUV",
    price_per_day: 75,
    capacity: 7,
    brand: "Nissan",
    image: require('../asset/imagesFolder/sedanCar.jpg'),
  },
  {
    id: 6,
    type: "Compact",
    price_per_day: 40,
    capacity: 4,
    brand: "Hyundai",
    image: require('../asset/imagesFolder/sedanCar.jpg'),
  },
  {
    id: 7,
    type: "Luxury",
    price_per_day: 120,
    capacity: 5,
    brand: "BMW",
    image: require('../asset/imagesFolder/sedanCar.jpg'),
  },
  {
    id: 8,
    type: "Convertible",
    price_per_day: 95,
    capacity: 2,
    brand: "Mazda",
    image: require('../asset/imagesFolder/sedanCar.jpg'),
  },
  {
    id: 9,
    type: "Electric Car",
    price_per_day: 70,
    capacity: 5,
    brand: "Tesla",
    image: require('../asset/imagesFolder/cat1.png'),
  },
  {
    id: 10,
    type: "Mini Van",
    price_per_day: 65,
    capacity: 6,
    brand: "Kia",
    image: require('../asset/imagesFolder/dog1.png'),
  },
];
